### ISSUE TITLE
conditionalPanels not working properly

### ISSUE THREAD

**Issue by sachitsaksena** [gimelbrantlab/magic#1]
Need to update conditionalPanels to properly display relevant elements of ui in both server-process.R and ui-process.R

`sidebarLayout(
           fluidRow(column(6,
                           radioButtons("choosePath",
                                       "Choose a model",
                                       choices = c("Generate new model",
                                                    "Use existing model"),
                                       selected = "Use existing model"
                                      )
           )),`

**Comment by kintany** [comment]
Fixed
