### ISSUE TITLE
Add default values in Shiny Generate

### ISSUE THREAD

**Issue by svigneau** [gimelbrantlab/magic#10]
It would be convenient to have default values in Shiny Generate tab for the "Upload file with processed chromatin data" and " Select models to train" fields. These could be "joined_scores_percentile_full_dataset.txt" and "glmStepAIC", respectively.

**Comment by kintany** [comment]
It is impossible to pre-select files for upload due to security reasons.

**Comment by kintany** [comment]
Fixed with switching from fileInput to Shiny Files file path selection
